fix: Adding missing 'handler' to go provider template
```
❯ ./run.sh
./main.go:112:2: undefined: handler
```

Signed-off-by: Lucas Fontes <lucas@cosmonic.com>