fix(wash): alias deprecated --enable-meters
We made a breaking change on main but this has not yet been released.
Adding in this alias keeps it from being breaking.

$ wash --enable-meters inspect x.wasm
WARN `--enable-meters` is deprecated, use `--meters fuel` instead
$ wash --enable-meters --meters epoch inspect x.wasm
error: the argument '--enable-meters' cannot be used with '--meters <METERS>'

Signed-off-by: Bailey Hayes <bailey@cosmonic.com>